server:
  port: 8080
  tomcat:
    max-threads: 500

spring:
  datasource:
    url: jdbc:mysql://192.168.202.184:3306/seata_storage
    username: otter
    password: JDAcQS3x9S0B2U5icM4h
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: seata-at-rm-two
eureka:
  client:
    service-url:
      defaultZone: http://192.168.202.137:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

#====================================Seata Config===============================================
seata:
  # 关闭自动代理
  enable-auto-data-source-proxy: false
  ## 配置中心采用apollo
  config:
    type: apollo
    apollo:
      apollo-meta: http://apollo-meta-dev.fe.host.dxy:88
      app-id: seata-demo
      namespace: framework.seata-common
  ## 注册中心采用redis
  registry:
    type: eureka
    eureka:
      application: seata-server
      service-url: http://192.168.202.137:8761/eureka
  tx-service-group: my_test_tx_group

